"""initial schema: users, wallets, assets, trading_pairs

Revision ID: f45ed1946413
Revises: 
Create Date: 2026-08-27 18:53:02.031674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f45ed1946413'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('is_fiat', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'trader', 'manager', 'admin', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('trading_pairs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('base_asset_id', sa.String(length=36), nullable=False),
    sa.Column('quote_asset_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('price_precision', sa.Integer(), nullable=False),
    sa.Column('qty_precision', sa.Integer(), nullable=False),
    sa.Column('min_qty', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'delisted', name='pairstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['base_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['quote_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_pairs_base_asset_id'), 'trading_pairs', ['base_asset_id'], unique=False)
    op.create_index(op.f('ix_trading_pairs_quote_asset_id'), 'trading_pairs', ['quote_asset_id'], unique=False)
    op.create_index(op.f('ix_trading_pairs_symbol'), 'trading_pairs', ['symbol'], unique=True)
    op.create_table('wallets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('spot', 'funding', name='wallettype'), nullable=False),
    sa.Column('balance', sa.Numeric(precision=40, scale=12), nullable=False),
    sa.Column('available', sa.Numeric(precision=40, scale=12), nullable=False),
    sa.Column('frozen', sa.Numeric(precision=40, scale=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'asset_id', 'type', name='uq_wallet_user_asset_type')
    )
    op.create_index(op.f('ix_wallets_asset_id'), 'wallets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_asset_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_trading_pairs_symbol'), table_name='trading_pairs')
    op.drop_index(op.f('ix_trading_pairs_quote_asset_id'), table_name='trading_pairs')
    op.drop_index(op.f('ix_trading_pairs_base_asset_id'), table_name='trading_pairs')
    op.drop_table('trading_pairs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
