"""add orders and trades

Revision ID: f534bdc35207
Revises: 25b5fa1e1723
Create Date: 2026-08-27 19:11:07.103017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f534bdc35207'
down_revision: Union[str, None] = '25b5fa1e1723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('pair_id', sa.String(length=36), nullable=False),
    sa.Column('side', sa.Enum('buy', 'sell', name='orderside'), nullable=False),
    sa.Column('type', sa.Enum('market', 'limit', name='ordertype'), nullable=False),
    sa.Column('price', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('qty', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('filled_qty', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('avg_fill_price', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('status', sa.Enum('open', 'filled', 'partially_filled', 'cancelled', 'rejected', name='orderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pair_id'], ['trading_pairs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_pair_id'), 'orders', ['pair_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('pair_id', sa.String(length=36), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('qty', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('notional', sa.Numeric(precision=38, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['pair_id'], ['trading_pairs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_order_id'), 'trades', ['order_id'], unique=False)
    op.create_index(op.f('ix_trades_pair_id'), 'trades', ['pair_id'], unique=False)
    op.create_index(op.f('ix_trades_user_id'), 'trades', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_user_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_pair_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_order_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_pair_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
